# Step 0 : Setting up

# Generals settings
language: node_js
sudo: required

# Services required to go trought
services:
  - docker

env:
  - version=1

# Step 1: Testing (web client only)

before_install:

  # Build temporary image 
  - docker build -t gradedjestrisk/multi-docker-test -f ./client/Dockerfile.dev ./client

script:

  # Run tests on temporay image
- docker run gradedjestrisk/multi-docker-test npm test -- --coverage


# Step 2 : Pushing all images to DockerHub

after_success:

  # Building images
  - docker build -t "$DOCKER_ID"/multi-client:$version ./client
  - docker build -t "$DOCKER_ID"/multi-nginx  ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker
  
  # Loggin in
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Pushing images
  - docker push "$DOCKER_ID"/multi-client:$version
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker
